## Numpy

In [7]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []



for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


In [15]:
import numpy as np
array_two = np.arange(1,4) **2
array_three = np.arange(1,4)**3
print(array_two + array_three)

[ 2 12 36]


In [24]:
sample_array = np.array([1,2,3])

*Power*

In [25]:
np.power(sample_array,2)

array([1, 4, 9])

*Negative*

In [27]:
np.negative(sample_array)

array([-1, -2, -3])

*Log*

In [28]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

*Sin*

In [31]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

### Multidimensional array

In [32]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array()